### ISSUE TITLE
Pursuit hits Gardevoir Super Effective / Calm Mind fails.

### ISSUE THREAD

**Issue by Crackz66** [pokebotred/pokebotwiki#14]
Pursuit (and probably other dark moves) can hit Gardevoir Super effective , even if her Fairy type should cover it. Probably applies to other mons , like Mr Mime

Calm Mind failed in one battle when Gardevoir used it , the turn before enemy pokemon was Paralyzed so it couldn't move.

**Comment by bausshf** [comment]
Fixed in patch 74.
