### ISSUE TITLE
Too Cool Acheivement

### ISSUE THREAD

**Issue by Try4se** [pokebotred/pokebotwiki#17]
Achievement is bugged

**Comment by Try4se** [comment]
https://www.facebook.com/pokebotred/photos/a.698345937287895/749012218887933/?type=3&comment_id=749012622221226&reply_comment_id=749014822221006&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by bausshf** [comment]
Thank you! It was trying to add it to the opponent's user (which of course didn't exist.) - It has now been fixed and I will manually add the achievement to your user.
