### ISSUE TITLE
Triple EXP-Dex not found

### ISSUE THREAD

**Issue by Try4se** [pokebotred/pokebotwiki#20]
Try4seToday at 8:09 AM
!pokestore Triple EXP-Dex
 
pokebotredBOTToday at 8:09 AM
@Try4seCould not find the product in the store.

![expdex](https://user-images.githubusercontent.com/54107998/63211548-9a855e00-c0c6-11e9-9411-63be66514443.png)

**Comment by bausshf** [comment]
Dang, thought I had fixed that already.

**Comment by bausshf** [comment]
Okay, fixed in patch 74. Forgot to update the actual store names. So it couldn't find the price.
