### ISSUE TITLE
Hp display issue?

### ISSUE THREAD

**Issue by ReyH17** [pokebotred/pokebotwiki#51]
![Surfachu1](https://user-images.githubusercontent.com/54775372/64079552-ecf38b00-cd12-11e9-830c-856db5240ff9.png)
![Surfachu 2](https://user-images.githubusercontent.com/54775372/64079556-f7158980-cd12-11e9-95d6-00d7bfe88a3a.png)

It always been like this every time it got a new level

**Comment by bausshf** [comment]
Fixed in next patch.
