### ISSUE TITLE
When I try to buy over 99 items like a dumbass, my money is stolen

### ISSUE THREAD

**Issue by Lelorthemerciless** [pokebotred/pokebotwiki#59]
If I try to buy too many great balls, bringing me over the 99 max, the shop takes the money from me anyway as if I had really bought the 150 great balls I tried to buy.

Suggestion: have the shop reject someone, or only take the money or what they have room for.

figures 
![Screen Shot 2019-09-06 at 7 12 53 PM](https://user-images.githubusercontent.com/54506706/64468499-71128d80-d0da-11e9-8eab-bd45918fadec.png)
![Screen Shot 2019-09-06 at 7 12 59 PM](https://user-images.githubusercontent.com/54506706/64468500-7374e780-d0da-11e9-99fe-baea0e0a1fd8.png)
![image](https://user-images.githubusercontent.com/54506706/64468532-9bfce180-d0da-11e9-8d5d-964f74b1fa0e.png)

![Screen Shot 2019-09-06 at 7 13 05 PM](https://user-images.githubusercontent.com/54506706/64468501-753eab00-d0da-11e9-8d63-6b6afce9d9d3.png)
![Screen Shot 2019-09-06 at 7 13 10 PM](https://user-images.githubusercontent.com/54506706/64468502-77a10500-d0da-11e9-84af-e4688c465396.png)
![Screen Shot 2019-09-06 at 7 13 18 PM](https://user-images.githubusercontent.com/54506706/64468504-7a035f00-d0da-11e9-93ba-fa513fdbc808.png)

**Comment by bausshf** [comment]
Fixed in next update and money will be returned :)
