### ISSUE TITLE
Contest Bug

### ISSUE THREAD

**Issue by asseaterx** [pokebotred/pokebotwiki#75]
![Screenshot_20190925-193612~2](https://user-images.githubusercontent.com/54383829/65601205-dc5dca00-dfcb-11e9-84d4-527b33444be8.png)

Other pokemon missed the secondary judgement when Player's pokemon do a move combination

**Comment by Rafilshah** [comment]
After a Pokemon does a move combo, no other pokemon is allowed to show off a move. Still a bug.
