### ISSUE TITLE
Suggestion: !pokemons SortName/SortLevel true (also sorting !inventory, is possible)

### ISSUE THREAD

**Issue by HeavenlyKnight** [pokebotred/pokebotwiki#80]
When you have plenty kind of items, maybe its hard to specific item

Maybe we can sorty it by Pokeball->Potions->Evolve Item->TMs->Other

Or anything else

**Comment by Rafilshah** [comment]
Sorting by level is already implemented. 
Inventory sorting is a needed feature.
